apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seekstar-app-tls
spec:
  secretName: seekstar-app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: seekstar.app
  dnsNames:
    - seekstar.app
    - www.seekstar.app
